name: hello word 
on: 
 push: 
   paths:
     - '!README.md'
     - '!doc/**'     
     - '**.cs'     
   branches: 
   - 'main'
   - 'demo1'
   - '!demo2'
   workflow_dispatch
jobs: 
  say-hello:
    runs-on: ubuntu-latest
    steps:
        - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
        - run: echo Hello Word, today is $TODAY
